apiVersion: v1
kind: Template
metadata:
  name: amun-inspect-buildconfig
  annotations:
    description: A template for BuildConfig to create build on the fly.
    openshift.io/display-name: Amun inspect BuildConfig
    version: 0.0.1
    tags: poc,amun,thoth,ai-stacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      A template used to create dynamic builds on user requests.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: amun-inspect-buildconfig
    app: amun
    component: inspect-buildconfig

objects:
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "${AMUN_INSPECTION_ID}"
      labels:
        app: amun
        component: inspect-buildconfig
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: "${AMUN_INSPECTION_ID}:latest"
      source:
        dockerfile: "${AMUN_GENERATED_DOCKERFILE}"
        type: Dockerfile
      resources:
        limits:
          memory: '512Mi'
          cpu: '500m'
        requests:
          memory: ${AMUN_BUILD_CPU}
          cpu: ${AMUN_BUILD_MEMORY}
      strategy:
        type: Docker
      triggers:
        - type: ConfigChange
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: CPU_FAMILY
                  operator: In
                  values:
                    - ${cpu_family}
                - key: CPU_MODEL
                  operator: In
                  values:
                    - ${cpu_model}
                - key: PHYSICAL_CPUS
                  operator: In
                  values:
                    - ${physical_cpus}
                - key: processor
                  operator: In
                  values:
                    - ${processor}

parameters:
  - name: AMUN_INSPECTION_ID
    description: Id of inspection that is run.
    displayName: Inspection id
    required: true

  - description: The content of Dockerfile to be built.
    displayName: Generated Dockerfile
    required: true
    name: AMUN_GENERATED_DOCKERFILE

  - name: AMUN_BUILD_CPU
    description: CPU cores requested for running job
    displayName: Job CPU
    default: 500m

  - name: AMUN_BUILD_MEMORY
    description: Memory requested for running job
    displayName: Job Memory
    default: 512Mi

  - name: cpu_family
    description: Family number of CPU
    displayName: CPU Family
    default: 6

  - name: cpu_model
    description: Modelnumber of CPU
    displayName: CPU model
    default: 85

  - name: physical_cpus
    description: NUmber of physical CPUS
    displayName: Physical CPUS
    default: 16

  - name: processor
    description: Name of processor
    displayName: Processor
    default: "Intel Xeon Processor (Skylake, IBRS)"
