kind: Template
apiVersion: v1
metadata:
  name: amun-inspect-job
  annotations:
    description: Amun - Execution engine for Thoth
    openshift.io/display-name: Amun API
    version: 0.0.1
    tags: poc,amun,thoth,ai-stacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines resources needed to run Amun's inspection job on OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: amun-inspect-job
    app: amun
    component: amun-inspect

objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: "${AMUN_INSPECTION_ID}"
      labels:
        app: amun
        component: amun-inspect
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: amun
            component: amun-inspect
        spec:
          automountServiceAccountToken: false
          restartPolicy: Never
          containers:
            - name: inspect
              env: []
              image: '${AMUN_INSPECTION_ID}:latest'
              livenessProbe:
                failureThreshold: 1
                initialDelaySeconds: 3600
                periodSeconds: 10
                tcpSocket:
                  port: 80
              resources:
                requests:
                  cpu: ${AMUN_JOB_CPU}
                  memory: ${AMUN_JOB_MEMORY}
                limits:
                  cpu: '750m'
                  memory: '256Mi'
              volumeMounts:
                - mountPath: /home/amun/hwinfo
                  name: hw-info-volume
          initContainers:
            - name: inspect-hwinfo
              image: inspect-hwinfo
              volumeMounts:
                - mountPath: /home/amun/hwinfo
                  name: hw-info-volume
          volumes:
            - name: hw-info-volume
              emptyDir: {}
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames: [inspect]
            from:
              kind: ImageStreamTag
              name: '${AMUN_INSPECTION_ID}:latest'

parameters:
  - name: AMUN_INSPECTION_ID
    description: Id of inspection that is run.
    displayName: Inspection id
    required: true

  - name: AMUN_JOB_CPU
    description: CPU cores requested for build
    displayName: Build CPU
    default: '750m'

  - name: AMUN_JOB_MEMORY
    description: Memory requested for build
    displayName: Build Memory
    default: '256Mi'
