apiVersion: v1
kind: Template
metadata:
  name: amun-secret
  annotations:
    description: This is Amun Secrets definition.
    openshift.io/display-name: Amun Secrets
    version: 0.0.1
    tags: poc,amun,thoth,ai-stacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: This template defines secrets required to deploy Amun.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    app: amun
    template: amun-secret
    component: secret

objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: amun
    labels:
      app: amun
      component: secret
  stringData:
    app-secret-key: ${AMUN_APP_SECRET_KEY}

parameters:
  - description: Secret key for flask application to have secured session connections.
    displayName: App secret key
    required: true
    name: AMUN_APP_SECRET_KEY
